### ISSUE TITLE
Add local storage for lower and upper tempo limits.

### ISSUE THREAD

**Issue by dcallus** [fillmaster/fillMaster#14]
On screen one where you choose your lower and upper tempo limits. This should be saved in local storage so that it remains the same after the app is closed.

**Comment by dcallus** [comment]
and time signature

**Comment by dcallus** [comment]
https://www.w3schools.com/html/html5_webstorage.asp

**Comment by ricci2511** [comment]
I could do a pull request for it if nobody is working on it

**Comment by dcallus** [comment]
complete
