### ISSUE TITLE
Add local storage for time signature and reset option

### ISSUE THREAD

**Issue by dcallus** [fillmaster/fillMaster#27]
Please add local storage options for time signatures so that the user's preference is saved.
Follow practices in [PR#25](url)https://github.com/fillmaster/fillMaster/pull/25

Rename the RESET TO DEFAULTS button in the settings menu to 'RESET ALL SETTINGS' and make it apply to the play settings (as well as those already reset in the settings menu). i.e.
make sure it also:
1. Resets tempo slider to 60 - 120
2. Resets time signature to 4/4

**Comment by ricci2511** [comment]
Hi again, since I did the previous LocalStorage thing I think I could look into this too. 
From my understanding you have a `DEFAULTS` object in `App.tsx` and a `resetAllSettings` function to reset to those values. 
Should I add a tempo slider and time signature key value pair in that DEFAULTS object and handle its reset in the `resetAllSettings` function? 

That would be one solution to the problem, but I'm not sure if you have something else in mind.

**Comment by dcallus** [comment]
Hmmm. I'm not sure actually. I'll have a think tomorrow and let you know. Thanks for asking.

**Comment by chrisd1999** [comment]
@dcallus I have added an PR recently, storing in `DEFAULTS` would not make sense, as they are defaults for the drawer itself. I have implemented reset settings with an custom event, which I guess is the best solution, without refactoring a lot of the app, and moving to global state.

**Comment by dcallus** [comment]
Thanks @chrisd1999 

Looks great. I'll have a proper look tomorrow. I need to go to bed shortly as its around midnight here in Scotland, can't believe how busy it's been today with everyone chipping in :) 

Thanks so much for your contribution.

I don't suppose you know how I can look at PR's from forked repos locally? As in, run the code before I merge?
I've looked up the issue and it seems it's possible to do via setting a new upstream origin and connecting to your branch, for example, but I get the error that I have already an origin set. It seems I may need to change the name of MY origin. I'll maybe try that tomorrow. Then it seems the next thing is to push my develop into your branch? Which seems a bit odd.

What's the usual process do you know?
