### ISSUE TITLE
UI bug: Bar disappears from screen on desktop

### ISSUE THREAD

**Issue by dcallus** [fillmaster/fillMaster#44]
the word Bar (and subsequent bar number and total bar number) disappear off the screen when used in a wide desktop.

Resize the window from min to max width and you will see it disappearing.

Not sure if it's related but max-width: 580px; in the body (index.css) is not quite right as when you click the menu it comes in from the far right of the screen whereas it should be coming in from the edge of the app (580px from left). I've tried it in on html as well and it won't work.

Would like to have both of these fixed, but if someone can just short the 'bar' text as that's much more important and I'll raise a separate issue for the other issue if they can't be solved together.

**Comment by ricci2511** [comment]
I'll take it, looks like the bar number thing happens because of the applied `padding-left`, since it is in a flex container it should be fixed by replacing `padding-left: 70vw` with `justify-content: flex-end`.
I'll also look into the sidebar issue and maybe do a pull request for both.
